[build]
  command = "npm ci && npm run build"
  publish = "dist"

# Vue Router SPA fallback
[[redirects]]
  from = "/api/*"
  to = "https://app.kipdesky.com/api/:splat"
  status = 200
  force = true

