[build]
  command = "npm ci && npm run build"
  publish = "dist"

# proxy API -> your backend
[[redirects]]
  from = "/api/*"
  to   = "https://app.kipdesky.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
